runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: public/image/favicon.ico
  upload: public/image/favicon.ico

- url: /public
  static_dir: public

- url: /bitbucket
  static_dir: dist

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest