runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: public/image/favicon.ico
  upload: public/image/favicon.ico

- url: /bitbucket/(.*\.(css|json|html|js|map|png))
  static_files: dist/\1
  upload: dist/(.*\.(css|json|html|js|map|png))

- url: /bitbucket/?(.*?)
  static_files: dist/index.html
  upload: dist/index.html

- url: /public
  static_dir: public

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest